cinema_homepage:
    path:     /
    defaults: { _controller: cinemaBundle:Default:index }
readfilm:
    path:     /readfilm
    defaults: { _controller: cinemaBundle:film:read}
readFilmGuest:
    path:     /readFilmGuest
    defaults: { _controller: cinemaBundle:film:readFilmGuest}
readFilmClient:
    path:     /readFilmClient
    defaults: { _controller: cinemaBundle:film:readFilmClient}
createfilm:
    path:     /create
    defaults: { _controller: cinemaBundle:film:create}
updatefilm:
    path:     /update/{id}
    defaults: { _controller: cinemaBundle:film:update}
esprit_parc_find1:
    path:     /find1
    defaults: { _controller: cinemaBundle:film:findNomDQL}
esprit_rech_find2:
    path:     /find2/{nom}
    defaults: { _controller: cinemaBundle:film:findNomDQL2}
deletefilm:
    path:     /delete/{id}
    defaults: { _controller: cinemaBundle:film:delete}
favorisfilm:
    path:     /fav/{user},{id}
    defaults: { _controller: cinemaBundle:favoris:favorisFilm}
deletefavorisfilm:
    path:     /delete1/{id}
    defaults: { _controller: cinemaBundle:favoris:delete}
favoris:
    path:     /favoris
    defaults: { _controller: cinemaBundle:favoris:read}
rechfilm:
    path:     /recherche
    defaults: { _controller: cinemaBundle:film:rech}
rechfil:
    path:     /aff
    defaults: { _controller: cinemaBundle:film;affiche}



affichefav:
    path:     /affichefav/{iduser}
    defaults: { _controller: cinemaBundle:favoris:affiche}











readsalle:
    path:     /readsalle
    defaults: { _controller: cinemaBundle:salle:read}

readSalleGuest:
    path:     /readSalleGuest
    defaults: { _controller: cinemaBundle:salle:readSalleGuest}

createsalle:
    path:     /createsalle
    defaults: { _controller: cinemaBundle:salle:create}

updatesalle:
    path:     /updatesalle/{id}
    defaults: { _controller: cinemaBundle:salle:update}



deletesalle:
    path:     /deletesalle/{id}
    defaults: { _controller: cinemaBundle:salle:delete}
Ajout:
    path: /Ajout
    defaults: { _controller: cinemaBundle:Avis:Ajout }

StatAvis:
    path:     /StatAvis
    defaults: { _controller: cinemaBundle:Avis:index }



ratefilm:
    path: /rate/{id},{nom}
    defaults: { _controller: cinemaBundle:rate:rateFilm }
rateReadFilm:
    path: /rateRead
    defaults: { _controller: cinemaBundle:rate:read }

