<?php
/**
 * Created by PhpStorm.
 * User: Houssem
 * Date: 21/02/2019
 * Time: 7:51 PM
 */

namespace cinemaBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * avisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class avisRepository extends EntityRepository
{
    
}