<?php

namespace cinemaBundle\Repository;
use cinemaBundle\Entity\favoris;
/**
 * favorisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class favorisRepository extends \Doctrine\ORM\EntityRepository
{
    public function rechDQL($iduser)
    {

        $query=$this->getEntityManager()
            ->createQuery("Select m from cinemaBundle:favoris m WHERE m.iduser= $iduser");
        return $query->getResult();
        }

    
}
